name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 16.x

      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Run Typescript Checks
        run: yarn lint --no-fix

      - name: Build Web App
        run: yarn build

      - name: Build Legacy Web App
        run: yarn build --dest dist-legacy
        env:
          CONTEXT: production
          VUE_APP_GOOGLE_ANALYTICS_ID: UA-97117718-6

      # See https://github.com/marketplace/actions/github-pages-action
      - name: 🚀 deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          force_orphan: true
          github_token: ${{ secrets.SLICERBOT_GITHUB_TOKEN }}
          publish_dir: ./dist-legacy
          publish_branch: slicer-kitware-com
          user_name: 'Slicer Bot'
          user_email: 'slicerbot@users.noreply.github.com'
