name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 16.x

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Run Typescript Checks
        run: yarn lint --no-fix

      - name: Build Web App
        run: yarn build

      - name: Build Legacy Web App
        run: yarn build --dest dist-legacy
        env:
          CONTEXT: production
          VUE_APP_GOOGLE_ANALYTICS_ID: UA-97117718-6

      # See https://github.com/marketplace/actions/github-pages-action
      - name: 🚀 deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          force_orphan: true
          github_token: ${{ secrets.SLICERBOT_GITHUB_TOKEN }}
          publish_dir: ./dist-legacy
          publish_branch: slicer-kitware-com
          user_name: 'Slicer Bot'
          user_email: 'slicerbot@users.noreply.github.com'
